### ISSUE TITLE
IE 11 / Edge: No style tags are beeing applied

### ISSUE THREAD

**Issue by queckezz** [micro-js/apply-styles#1]
Using vdux in IE, no `style` tags are beeing applied. I've tracked down the problem to this module. There is a problem using `@f/has` with `node.style`. `hasOwnProperty` is returning true for each property check in chrome but not in IE. No idea why, since the properties are there and not even on the prototype :confused:

I'm dropping in a `console.log` in the `applyStyles` function to log which css properties are supported:

![image](https://cloud.githubusercontent.com/assets/2580598/13862195/f6d6f072-ec91-11e5-97ce-0b8b52d30a73.png)

We can see the following expected output in chrome (and mobile chrome):

![image](https://cloud.githubusercontent.com/assets/2580598/13862165/c0e6eb7a-ec91-11e5-8700-bd727a5f0985.png)

However, in IE it's logging for all properties `false`:

![image](https://cloud.githubusercontent.com/assets/2580598/13862210/20705a86-ec92-11e5-8e8b-a55bcc3af0bd.png)

Possible solution would be to swap out `hasOwnProperty` with an `in` check:

``` js
if (key in style) { // returns also true in IE

}
```

**Update:** Related, http://stackoverflow.com/questions/34857955/hasownpropertygetcomputedstyle-false-in-ie-11

**Comment by ashaffer** [comment]
Huh, that's pretty weird and bad. I'd like to understand what IE's deal is with hasOwnProperty first I think. If you call `style.hasOwnProperty(key)` rather than using `has(key, style)` does it return true?

**Comment by queckezz** [comment]
Sadly, it's still false even with `style.hasOwnProperty(key)`

Simple case is working though

``` js
const a = { b: 'c' }
console.log(a.hasOwnProperty('b')) // true in IE
console.log(has('b', a)) // true in IE
```

**Comment by ashaffer** [comment]
Hmm i'm not seeing this behavior. Is there anything special about your IE environment?

**Comment by ashaffer** [comment]
Are you by any chance running IE in compatibility mode for an older version?

**Comment by ashaffer** [comment]
Oh shit lol. I see the bug. 

`if (has(key, style)) {`

Ought to be

`if (has(key, styles)) {`

It was purely coincidental that it was working on Chrome - IE must just not put those as own properties on the node's style object. Nasty little typo there.

**Comment by queckezz** [comment]
Oh wow, so simple. Thanks man!
